CREATE TABLE stocks(
    "id" serial primary key,
    "Name" varchar(30),
    "CMP Rs." float,
    "Mar Cap Rs.Cr." float,
    "Div Yld %" float,
    "NP Qtr Rs.Cr." float,
    "Qtr Profit Var %" float,
    "Qtr Sales Var %" float,
    "ROCE %" float,
    "Sales Rs.Cr." float,
    "ROE %" float,
    "Sales growth %" float,
    "Profit growth %" float,
    "No. of Share Holders" float,
    "Sales Var 3Yrs %" float,
    "EPS 12M Rs." float,
    "EV / EBITDA" float,
    "RSI" float
)

CREATE TABLE stocks(
    id serial primary key,
    Name varchar,
    CMP_Rs float,
    Mar_Cap_RsCr float,
    Div_Yld_% float,
    NP_Qtr_RsCr float,
    Qtr_Profit_Var_% float,
    Qtr_Sales_Var_% float,
    ROCE_% float,
    Sales_RsCr float,
    ROE_% float,
    Sales_growth_% float,
    Profit_growth_% float,
    No_of_Share_Holders float,
    Sales_Var_3Yrs_% float,
    EPS_12M_Rs float,
    EV_/_EBITDA float,
    RSI float,
)