CREATE TABLE stocks(
    id serial primary key,
    Name varchar(30),
    CMP_Rs numeric,
    Mar_Cap_RsCr numeric,
    Div_Yld_PERCENT numeric,
    NP_Qtr_RsCr numeric,
    Qtr_Profit_Var_PERCENT numeric,
    Qtr_Sales_Var_PERCENT numeric,
    ROCE_PERCENT numeric,
    ROE_PERCENT numeric,
    Sales_growth_PERCENT numeric,
    Profit_growth_PERCENT numeric,
    No_of_Share_Holders numeric,
    EPS_12M_Rs numeric,
    EV_BY_EBITDA numeric,
    RSI numeric,
    Current_ratio numeric,
    Debt_BY_Eq numeric
)

CREATE TABLE stocks(
    id serial primary key,
    Name varchar,
    CMP_Rs float,
    Mar_Cap_RsCr float,
    Div_Yld_% float,
    NP_Qtr_RsCr float,
    Qtr_Profit_Var_% float,
    Qtr_Sales_Var_% float,
    ROCE_% float,
    Sales_RsCr float,
    ROE_% float,
    Sales_growth_% float,
    Profit_growth_% float,
    No_of_Share_Holders float,
    Sales_Var_3Yrs_% float,
    EPS_12M_Rs float,
    EV_/_EBITDA float,
    RSI float,
)